ENABLE:
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML
  
ENABLE_LINTERS:
  - PYTHON_RUFF

DISABLE_LINTERS:
  - YAML_V8R

JSON_PRETTIER_ARGUMENTS: ["--trailing-comma", "none"]
